### ISSUE TITLE
Ignoring hidden entities

### ISSUE THREAD

**Issue by ScottG489** [jazzyisj/unavailable-entities-sensor#13]
Is there a way to ignore hidden entities?

I believe related to a recent change to HA, some of my energy cost sensors report unknown after reboot until they have some energy to report (e.g. a light that hasn't been turned on since restarting HA).

Any suggestions on how this could be done?

Also thanks for this great project! :)

**Comment by jazzyisj** [comment]
You're welcome!

As far as I know hidden entities are just for the UI.  Being hidden doesn't affect the entity in the state machine so it doesn't impact this sensor.  I would just add a search filter those entities if they have something in common in the name or add them to your ignored entities group if you do not wish them to be monitored.
