### ISSUE TITLE
Any way to ignore disabled entities?

### ISSUE THREAD

**Issue by flyize** [jazzyisj/unavailable-entities-sensor#17]
It would be nice to be able to just list things that are enabled. Things that are disabled are usually for a reason.

Thanks!

**Comment by jazzyisj** [comment]
I'm not sure what you mean here.  Disabled entities are not reported by this template or any other jinja template.  Hidden entities will be because they are just hidden from the front end, not the state machine.

What integration created the entity that is being erroneously reported?
