### ISSUE TITLE
automation gives error

### ISSUE THREAD

**Issue by chicco83** [jazzyisj/unavailable-entities-sensor#21]
hi. if i copy and paste the automation code HA gives the error "Message malformed: expected dictionary"

**Comment by jazzyisj** [comment]
That doesn't tell me much. Can you post the actual error from your log?  

Where and how did you paste the automation code?  Is the template sensor working correctly? Can you also post (and format) your automation code here?

**Comment by jazzyisj** [comment]
One month no response, issue closed.  If you still need assistance please reopen with additional details.
