### ISSUE TITLE
Issue installing package

### ISSUE THREAD

**Issue by mesayz** [jazzyisj/unavailable-entities-sensor#23]
Hello,
I am having problem installing the package. I have package enable on my HA. Here is the error message Im getting when I load configuration
----

A basic validation of the configuration is automatically done before restarting. The basic validation ensures the YAML configuration doesn't have errors which will prevent Home Assistant or any integration from starting. It's also possible to only do the basic validation check without restarting.
Configuration invalid!

Error loading /config/configuration.yaml: mapping values are not allowed here
in "/config/packages/package_unavailable_entities.yaml", line 28, column 66

**Comment by jazzyisj** [comment]
Sorry for delay, I've been out of commission for a couple monthis.

Did you get this figured out?  There doesn't seem to be an issue with the package itself.

**Comment by jazzyisj** [comment]
Closing issue.  Ask again if you're still having a problem.
