### ISSUE TITLE
Attributes unavailable 2023.4

### ISSUE THREAD

**Issue by uzi2git2** [jazzyisj/unavailable-entities-sensor#33]
The list of attributes showing the unavailable entities is not shown following the April update to HA

**Comment by uzi2git2** [comment]
Solved by changing
 attributes:
          entity_id: >

to                id:.>

Thanks @pedolsky

**Comment by jazzyisj** [comment]
They are available, they just don't show in the more-info dialogue.

I'll leave this here for now and I'll pin the issue until I decide if I'll change it in the git.

https://community.home-assistant.io/t/ha-2023-4-0-no-longer-shows-my-template-sensor-attribute-list/556978
