### ISSUE TITLE
Error n logs after quick reboot of ha

### ISSUE THREAD

**Issue by borodaaaaa** [jazzyisj/unavailable-entities-sensor#38]
Logger: homeassistant.helpers.template_entity
Source: helpers/template_entity.py:358 
First occurred: 20:11:41 (4 occurrences) 
Last logged: 20:11:41

TemplateError('TypeError: argument of type 'NoneType' is not iterable') while processing template 'Template<template=({{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group') |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|list|count }}) renders=74>' for attribute '_attr_native_value' in entity 'sensor.unavailable_entities'
TemplateError('TypeError: argument of type 'NoneType' is not iterable') while processing template 'Template<template=({{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group') |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|map(attribute='entity_id')|list }}) renders=74>' for attribute 'entities' in entity 'sensor.unavailable_entities'
TemplateError('TypeError: argument of type 'NoneType' is not iterable') while processing template 'Template<template=({{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group') |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|list|count }}) renders=12>' for attribute '_attr_native_value' in entity 'sensor.unavailable_entities'
TemplateError('TypeError: argument of type 'NoneType' is not iterable') while processing template 'Template<template=({{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group') |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|map(attribute='entity_id')|list }}) renders=12>' for attribute 'entities' in entity 'sensor.unavailable_entities'

**Comment by jazzyisj** [comment]
Are you still getting this?

**Comment by borodaaaaa** [comment]
Yes

**Comment by borodaaaaa** [comment]
Wonder if that is something to do with group file, I only use it for unavailable entities but it has some old ones that does not exist anymore

**Comment by borodaaaaa** [comment]
Sure mate will try to do it and let you know. Thank you for your response

**Comment by borodaaaaa** [comment]
That error is gone after I updated template and automation and group file. The new automation notification looks soo great! Thank you for such a great feature mate.

I still do have an error message when I try to do quick restart of HA. I dont think it is still related to Unavailable entries.  If so, please close the issue as resolved, Just in case I drop the error message here for you to look at.

Logger: homeassistant.components.websocket_api.http.connection
Source: loader.py:879
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:03:39 (1 occurrences)
Last logged: 10:03:39

[139651505134096] Integration 'l' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 930, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 339, in async_handle_reload_all
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 930, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/reload.py", line 176, in _reload_config
    await async_reload_integration_platforms(hass, domain, platforms)
  File "/usr/src/homeassistant/homeassistant/helpers/reload.py", line 53, in async_reload_integration_platforms
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/reload.py", line 63, in _resetup_platform
    integration = await async_get_integration(hass, integration_platform)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 879, in async_get_integration
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'l' not found.

**Comment by jazzyisj** [comment]
Interesting error.  You've got something going on with your installed integrations.  Looks like maybe one didn't get installed or uninstalled correctly maybe?  Anyway,  nothing to do with your unavailable entities sensor.

**Comment by borodaaaaa** [comment]
Cool thank you for confirmation and for your support. Have a lovely day mate!
