### ISSUE TITLE
Template sensor not updating

### ISSUE THREAD

**Issue by ghallford** [jazzyisj/unavailable-entities-sensor#43]
I added the manual template to my config to get light states of unavailable but the template is not updating. The sensor.unavailable_entities shows as unknown with no entities. 

If I test the template in the template dev console, I do get entities showing that are unavailable. Not sure what is wrong. I have restarted everything a few times. I have other templates that are working as expected.

Template code in configuration.yaml:

```
template:
  - sensor:
      - name: "Unavailable Entities"
        unique_id: unavailable_entities
        icon: "{{ iif(states(this.entity_id)|int(-1) > 0,'mdi:alert-circle','mdi:check-circle') }}"
        state_class: measurement
        unit_of_measurement: entities
        state: >
          {% set ignore_seconds = 60 %}
          {% set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
          {% set entities = states.light
              |rejectattr('last_changed','ge',ignore_ts)
              |rejectattr('entity_id','search','tablet_') %}
          {{ entities|map(attribute='entity_id')|reject('has_value')|list|sort }}

Entity state unknown (image attached)

Dev console, same code shows entities that are unavailable (image attached)

![Screenshot 2023-11-02 113519](https://github.com/jazzyisj/unavailable-entities-sensor/assets/17805839/5f527bbb-aab9-41cb-ab6d-15a340f8292a)
![Screenshot 2023-11-02 113455](https://github.com/jazzyisj/unavailable-entities-sensor/assets/17805839/fc721afc-e7d8-438d-b6e0-57981599c91f)

**Comment by ghallford** [comment]
I found an error in the Home Assistant log:

ValueError: Sensor sensor.unavailable_entities has device class 'None', state class 'measurement' unit 'entities' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '['light.office', 'light.office_bulb_1', 'light.office_bulb_2', 'light.office_bulb_3', 'light.office_bulb_4', 'light.office_bulb_5', 'light.office_bulb_6', 'light.office_light_1', 'light.office_light_2', 'light.office_light_3']' (<class 'homeassistant.helpers.template.gen_result_wrapper.<locals>.Wrapper'>)

**Comment by bcutter** [comment]
> I found an error in the Home Assistant log:
> 
> ValueError: Sensor sensor.unavailable_entities has device class 'None', state class 'measurement' unit 'entities' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '['light.office', 'light.office_bulb_1', 'light.office_bulb_2', 'light.office_bulb_3', 'light.office_bulb_4', 'light.office_bulb_5', 'light.office_bulb_6', 'light.office_light_1', 'light.office_light_2', 'light.office_light_3']' (<class 'homeassistant.helpers.template.gen_result_wrapper..Wrapper'>)

So how did you actually solve this?!?
