### ISSUE TITLE
Installation of package "unavailable-entities-sensor " failed

### ISSUE THREAD

**Issue by sydney2711** [jazzyisj/unavailable-entities-sensor#45]
After enabling packages and downloading the yaml file into the newly created folder the check before restarting HA came back with
"no integration packages" found.
After restart of HA the log reads

Home Assistant Core
Setup failed for 'packages': Integration not found.
10:05:52 – (ERROR) setup.py

I am running the following system

Core 2023.12.0
Supervisor 2023.12.0
Operating System 11.1
Frontend 20231206.0

Is there anything I can change to get this nice package running.

Cheers Christian

**Comment by jazzyisj** [comment]
Did you put "packages" under homeassistant **at the top** of your configuration.yaml file?  
Are you sure the folder you created is the same name as specified in the configuration.yaml?

```
homeassistant:
  packages: !include_dir_named packages
```

If you don't figure out the error first, copy and paste the relevant section of your configuration.yaml file here.

**Comment by jazzyisj** [comment]
No reply.  Closed.
