### ISSUE TITLE
Code versioning

### ISSUE THREAD

**Issue by alanmilinovic** [jazzyisj/unavailable-entities-sensor#46]
It would be great if tag or release from github is used for this project. Just an idea. Great stuff you are doing by the way. Thank you!

**Comment by jazzyisj** [comment]
Sure I could look into that.  I don't really anticipate any more significant changes but it would definitely make it easier to figure out when something has changed.

**Comment by jazzyisj** [comment]
https://github.com/jazzyisj/unavailable-entities-sensor/releases
