### ISSUE TITLE
Creating the automation with Detailed Persistent Notification gives error

### ISSUE THREAD

**Issue by dnewell73** [jazzyisj/unavailable-entities-sensor#53]
The error I'm getting is:
   Message malformed: extra keys not allowed @ data['automation']

**Comment by jazzyisj** [comment]
Did you add the sensor using the package method?

**Comment by dnewell73** [comment]
Yes I used the package method.  Under the entities page, is see a sensor called Unavailable Entities (sensor.unavailable_entities)

**Comment by jazzyisj** [comment]
Sorry for delay in responses.  Life is getting in the way right now.

Can you paste the entire error your are getting and attach your package file?  It looks like maybe you've copy and pasted incorrectly.

**Comment by dnewell73** [comment]
Well, I'm not sure what happened but I'm not getting the error any longer.   Thanks!
