### ISSUE TITLE
Example detailed_persistent_notification.yaml reports invalid syntax

### ISSUE THREAD

**Issue by snigehere** [jazzyisj/unavailable-entities-sensor#54]
Follow up to https://github.com/jazzyisj/unavailable-entities-sensor/issues/53

In the latest release of home assistant (2024.10.1) I see that the example posts errors around its syntax
```
    trigger:
      - platform: state
        entity_id: sensor.unavailable_entities
        attribute: entity_id
        to: 
```
and 
```
    action:
      - service: persistent_notification.create
        data:
```
both of the above reported invalid syntax  

I am not hot on yaml but believe it should be something like
```
trigger:
  - entity_id: sensor.unavailable_entities
    attribute: entity_id
    to: null
    trigger: state
```
and
```
actions:
  - action: persistent_notification.create
    data:
```
I am happy to be corrected if its wrong!

**Comment by jazzyisj** [comment]
Can you post the error you are getting please?  All you have done here is updated to the new syntax style.  The old style is still valid and should not throw errors.

**Comment by snigehere** [comment]
This is what I see 

![image](https://github.com/user-attachments/assets/7d1d3324-4da7-4508-966f-82427e58d52b)

It still seems to work but wanted to see if action was needed to re-work this for the future

**Comment by jazzyisj** [comment]
Thank you for reporting, but these are not actually syntax errors.   The old syntax will never be deprecated according to the 10.2024 release notes.  I have personally updated, and will update the package when I do the next release  I have a major update I've been testing.

Anyway, I'll bet that you have an update available for VSCode.  I'm assuming you're using the addon.  It shouldn't be showing those as syntax errors.  I think they had some trouble with that and released a couple of updates back to back.  You should be on v5.17.1  If your are using VSCode on a Windows machine, check to see if your Home Assistant Extension needs an update.  That should be v05:52:02.

Let me know if that was the problem so I can close it out.  Thanks!

**Comment by snigehere** [comment]
Many thanks for your work in looking at this.  Your code is invaluable in helping me manage my home assistant so I really appreciate the time you have given.

Yes - I have seen 5 updates to studio code server in the past 2 weeks which I have applied - The screen grab is from the studio code server add on within HA and I can confirm it shows "Current version: 5.17.1"

I am OK if you want to close this as I have already updated modified the code, and you have the change in progress so the issue will go away.  

An aside - 
If you have a new release in progress I wonder if a minor issue I see is solved - I am happy to open a different bug for this if it needs it or am also happy to continue looking myself before opening a bug.
When I get a notification about an entity going unavailable I will resolve it - when the trigger sees the change it runs again and I end up with an "sensor.unavailable_entities" is unavailable as a persistent notification - I can clear it and its then gone so its just a minor thing.  I am sure its a timing issue because if I look at sensor.unavailable_entities via developer tools it has a value of 0 so is defiantly not unavailable.   I tried adding the sensor to my exclusion list (there are 195 items in the list) but it didn't solve it which, to me, is further evidence on it being a timing issue.  Its on my "get to it" list for seeing if I can find the cause but I have not got to it yet 

Thanks again for sharing your solution and maintaining it.

**Comment by jazzyisj** [comment]
Very strange VSCode is highlighting those as errors for you and not me... or anyone else I assume since this is the first I've heard of it.

Maybe try adding sensor.unavailable_entities to your ignore group or in the template.
I'll see if I can get the update out in the next week or so.

**Comment by snigehere** [comment]
Ok - I now realise what I am left with is an empty unavailable entities persistent notification rather than a notification saying the unavailable entities sensor is unavailable ....

**Comment by jazzyisj** [comment]
Add a `for: 5 `parameter to the trigger.  That change is part of the new release.

https://github.com/jazzyisj/unavailable-entities-sensor/issues/50

```
    trigger:
      - platform: state
        entity_id: sensor.unavailable_entities
        attribute: entity_id
        to: 
        for: 5
```

**Comment by snigehere** [comment]
Thanks for the update - I set that and re-booted but unfortunately it did not solve the issue.

**Comment by jazzyisj** [comment]
Ha.  I think I just figured out what you did.  You're just using the detailed notification automation as is?  That automation is just an example to show you how to do the detailed notification.

Look at the automation in the package.  That one dismisses the notification if the state is below zero.  There is no logic in the detail example to dismiss or not send depending on the state of the sensor.

What you're meant to do is replace the "basic notification" in the package with the "detailed notification" in the package.

**Comment by snigehere** [comment]
Thank you .. your are right.. i just used the example notification in my automation.  I didn't spot that it needed additional code to work correctly.

I will go back and read in more detail and add the missing parts. 

My score is 5 for effort but 0 for reading.

Thanks again
