### ISSUE TITLE
Delay in executing automations

### ISSUE THREAD

**Issue by Amathagma** [jazzyisj/unavailable-entities-sensor#56]
Suddenly I noticed an increased execution time between automations.
First thing I suspected was the ssd as it had 88% remaining lifetime so I replaced it, no difference.
After that I thought what changes I made when I noticed this delay and I disabled this package. Everything is back to normal again and the execution time is instant again.
Don't know what can cause it though.
Raspberry Pi 4b, latest core 2024.12.0 running on SSD.

**Comment by jazzyisj** [comment]
I'm going to be releasing a new version which works a little differently and should be less resource intensive.  It is because we are constantly iterating the states object.  Stay tuned.  I'm going to pin this.

**Comment by jazzyisj** [comment]
Updated version released.  If you choose to update, please let me know if the new version resolves your issue.
