### ISSUE TITLE
new install throwing error "expected dictionary for dictionary value @ data['packages']"

### ISSUE THREAD

**Issue by knwpsk** [jazzyisj/unavailable-entities-sensor#6]
I'm a noob, please be gentle.
I carefully followed the readme instructions to install this package.
When I try to restart core, it throws the error:

```
The system cannot restart because the configuration is not valid: 
expected dictionary for dictionary value @ data['packages']
```

I'm running core v 2021.12.10
supervisor v 2021.12.2

Per the readme:
I added new directory "packages" in /config/packages
Uploaded the package file to /config/packages/

In my config.yaml I added the package line under the one other thing I had there:

homeassistant:
..media_dirs:
....local: /media
..packages: /config/packages 
    
--

I noticed one odd thing: when I open package_unavailable_entities.yaml in the file editor  (but don't touch, don't edit anything), it's showing an error (red ! in the top-right corner of the editor): 

`end of the stream or a document separator is expected at line 154, column 65:
     ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ... 
                                         ^`

**Comment by knwpsk** [comment]
p.s. I pasted the yaml file content into yamlchecker.com and it shows the error too.

`end of the stream or a document separator is expected (154:65)

 151 |  ... 
 152 |  ... 
 153 |  ... 
 154 |  ...  content="{"version": "4", "rollouts ...
------------------------------------------^
 155 |  ... he optimizely JS needs to be loaded in the
 156 |  ... ers -->`

**Comment by knwpsk** [comment]
Instead of what the readme here says, 
I followed what the Packages tutorial page says:

homeassistant:
..packages: !include_dir_named packages

Now I can get it to restart OK.

**Comment by jazzyisj** [comment]
Yikes!  The package instruction in the README was wrong, I'll update that.  Sorry about that, glad you figured it out.

As for your errors, you've got me stumped.  There are only 79 lines in the package, how do you have an error on line 154?  I think you have some formatting issue happening.  Plus, I have this exact copy of the package in my config and all is good.  How did you copy the file to your system?  I did notice and fix a little bug (unrelated to your issue) while I was looking into this so make sure you get the latest version when you try steps below.

So try this.

1.  Delete whatever files you have in your packages directory right now.  Leave the package configuration and directory in tact.  Restart Home Assistant.  What happens?

2.  If you have restarted successfully, use your file editor to create a BLANK file in the /config/packages directory.  Name that file package_unavailable_entities.yaml  (it actually doesn't matter what you name it as long as the extension is .yaml).

3. Come back to this git and click the[ package_unavailable_entities.yaml](https://github.com/jazzyisj/unavailable-entities-sensor/blob/main/package_unavailable_entities.yaml) file.  When on that file page click the RAW button.
![image](https://user-images.githubusercontent.com/44064559/151450200-747d12bc-830d-4c11-92d8-ebf140e990b4.png)

4. Your browser will open the raw unencoded file.  Click on the page somewhere and then click CTRL A to select the entire file contents, then CTRL C to copy them to the clipboard.

5. Open the blank package_unavailable_entities.yaml file you created in step 3.  Click CTRL A to select the entire file contents (there should be nothing there but this is good practice).  Click CTRL P to paste the contents of the clipboard to the file.  Save it.

6.  Check your configuration, it should pass.  Restart Home Assistant.

7. What happens?

**Comment by knwpsk** [comment]
Thanks Jazzy!
I see what I did. Somehow I downloaded an html representation of your yaml file.
I'm redoing it now.
(BTW, your steps 3 and 5 above are missing something about how to create the blank file... but I can handle it. Just please edit the comment for posterity.)

**Comment by jazzyisj** [comment]
> your step 5 above should point to step 2 about how to create the blank file

This is totally dependent on what file editor and/or operating system you are using.  
For Windows right click -> New -> Text Document will do the trick!

**Comment by knwpsk** [comment]
Yeah, checks out good now.

FWIW: when I right-click on the yaml filename in the main page, and "save link as" to download the file...
then open it and examine in notepad... it's a mess!  Downloads a bunch of html junk instead of just the raw file. 
I'm not what you'd call a frequent flier on github... but that sucks!

**Comment by jazzyisj** [comment]
When you save link as you are actually telling it to save the HTML file.  Always do the RAW trick for single files if you need multiple files download the zip and extract them from there.

Glad you got it going!

**Comment by knwpsk** [comment]
Thanks a lot, Jazzy.

**Comment by knwpsk** [comment]
Got this all working nicely now, and I have to say THANK YOU and I'm so impressed by what you guys have done and shared here.
