### ISSUE TITLE
Handle scenes starting HA Core 2022.2.0

### ISSUE THREAD

**Issue by bcutter** [jazzyisj/unavailable-entities-sensor#9]
Have a look at https://www.home-assistant.io/blog/2022/02/02/release-20222/#scenes-now-have-a-state

This leads to scenes being detected because of their state `unknown`. Not sure if
- this is only the case after updating to HA 2022.2 where a scene has not been used/activated yet
- or if this is always the case after a restart of HA

Scenes being activated get the timestamp as state, e. g. `2022-02-13T18:51:51.148547+00:00`.

**Comment by bcutter** [comment]
OK so... buttons will now behave the same, so there's no need to exclude them (unless you pressed all of them at least once)?

**Comment by jazzyisj** [comment]
Yep.  I've tested input_buttons, mqtt buttons, integration buttons.  They all retain the timestamp state once you've pressed them once.  I'm going to close this but feel free to let me know if something doesn't work as expected.
